# Generated by Django 5.1.2 on 2024-10-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='views_count',
            new_name='view_count',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='preview_image',
            field=models.ImageField(default='/images/default.jpg', upload_to='previews/'),
            preserve_default=False,
        ),
    ]
